In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import scipy.stats as stats

import os
for dirname, _, filenames in os.walk('C:/Users/Asus/Documents/S2/Datsci/World Happiness'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

C:/Users/Asus/Documents/S2/Datsci/World Happiness\2015.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2016.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2017.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2018.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2019.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2020.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2021.csv
C:/Users/Asus/Documents/S2/Datsci/World Happiness\2022.csv

In [2]:
YEARS = list(range(2015, 2023))
YEARS_RANGE = [min(YEARS), max(YEARS)]

In [3]:
def get_data(path):
    def read_csv(year):
        return pd.read_csv("{0}/{1}.csv".format(path, year)).assign(year=year)

    return pd.concat([
        read_csv(year) for year in YEARS
    ], ignore_index=True)

In [4]:
raw_df = get_data("C:/Users/Asus/Documents/S2/Datsci/World Happiness")
print(raw_df.shape)
raw_df.head()

(1231, 52)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 52 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     617 non-null    object
 1   Region                                      315 non-null    object
 2   Happiness Rank                              315 non-null    float64
 3   Happiness Score                             315 non-null    float64
 4   Standard Error                              158 non-null    float64
 5   Economy (GDP per Capita)                    315 non-null    float64
 6   Family                                      470 non-null    float64
 7   Health (Life Expectancy)                    315 non-null    float64
 8   Freedom                                     470 non-null    float64
 9   Trust (Government Corruption)               315 non-null    float64
 10  Generosity                                  1084 non-null   float64
 11  Dystopia Residual                           315 non-null    float64
 12  year                                        1231 non-null   int64
 13  Lower Confidence Interval                   157 non-null    float64
 14  Upper Confidence Interval                   157 non-null    float64
 15  Happiness.Rank                              155 non-null    float64
 16  Happiness.Score                             155 non-null    float64
 17  Whisker.high                                155 non-null    float64
 18  Whisker.low                                 155 non-null    float64
 19  Economy..GDP.per.Capita.                    155 non-null    float64
 20  Health..Life.Expectancy.                    155 non-null    float64
 21  Trust..Government.Corruption.               155 non-null    float64
 22  Dystopia.Residual                           155 non-null    float64
 23  Overall rank                                312 non-null    float64
 24  Country or region                           312 non-null    object
 25  Score                                       312 non-null    float64
 26  GDP per capita                              312 non-null    float64
 27  Social support                              614 non-null    float64
 28  Healthy life expectancy                     614 non-null    float64
 29  Freedom to make life choices                614 non-null    float64
 30  Perceptions of corruption                   613 non-null    float64
 31  Country name                                302 non-null    object
 32  Regional indicator                          302 non-null    object
 33  Ladder score                                302 non-null    float64
 34  Standard error of ladder score              302 non-null    float64
 35  upperwhisker                                302 non-null    float64
 36  lowerwhisker                                302 non-null    float64
 37  Logged GDP per capita                       302 non-null    float64
 38  Ladder score in Dystopia                    302 non-null    float64
 39  Explained by: Log GDP per capita            302 non-null    float64
 40  Explained by: Social support                448 non-null    object
 41  Explained by: Healthy life expectancy       448 non-null    object
 42  Explained by: Freedom to make life choices  448 non-null    object
 43  Explained by: Generosity                    448 non-null    object
 44  Explained by: Perceptions of corruption     448 non-null    object
 45  Dystopia + residual                         302 non-null    float64
 46  RANK                                        147 non-null    float64
 47  Happiness score                             146 non-null    object
 48  Whisker-high                                146 non-null    object
 49  Whisker-low                                 146 non-null    object
 50  Dystopia (1.83) + residual                  146 non-null    object
 51  Explained by: GDP per capita                146 non-null    object
dtypes: float64(36), int64(1), object(15)
memory usage: 428.0+ KB

In [6]:
raw_df.describe()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,...,Perceptions of corruption,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Ladder score in Dystopia,Explained by: Log GDP per capita,Dystopia + residual,RANK
count,315.000000,315.000000,158.000000,315.000000,470.000000,315.000000,470.000000,315.000000,1084.000000,315.000000,...,613.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,147.000000
mean,79.238095,5.378949,0.047885,0.899837,0.990347,0.594054,0.402828,0.140532,0.153545,2.212032,...,0.416267,5.502645,0.056111,5.612629,5.392641,9.363053,2.198127,0.922248,2.198290,74.000000
std,45.538922,1.141531,0.017146,0.410780,0.318707,0.240790,0.150356,0.115490,0.167592,0.558728,...,0.340490,1.092111,0.020292,1.074850,1.110534,1.180595,0.229201,0.391830,0.595958,42.579338
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,-0.300907,0.328580,...,0.000000,2.523000,0.025902,2.596000,2.449000,6.492642,1.972317,0.000000,0.257241,1.000000
25%,40.000000,4.510000,0.037268,0.594900,0.793000,0.419645,0.297615,0.061315,0.064828,1.884135,...,0.082000,4.769400,0.042000,4.885588,4.636008,8.483295,1.972317,0.633963,1.823000,37.500000
50%,79.000000,5.286000,0.043940,0.973060,1.025665,0.640450,0.418347,0.106130,0.162140,2.211260,...,0.306000,5.524500,0.052321,5.610132,5.426829,9.514612,1.972317,0.982509,2.223108,74.000000
75%,118.500000,6.269000,0.052300,1.229000,1.228745,0.787640,0.516850,0.178610,0.252000,2.563470,...,0.780623,6.248375,0.066000,6.362124,6.136381,10.356000,2.430000,1.241988,2.619750,110.500000
max,158.000000,7.587000,0.136930,1.824270,1.610574,1.025250,0.669730,0.551910,0.838075,3.837720,...,0.939000,7.842000,0.173000,7.904000,7.780000,11.647000,2.430000,1.751000,3.482000,147.000000

In [7]:
fixed_df = raw_df.copy()

fixed_df["Country"] = fixed_df["Country"].fillna(fixed_df["Country or region"]).fillna(fixed_df["Country name"])
fixed_df.drop(columns=["Country or region", "Country name"], inplace=True)
fixed_df = fixed_df[fixed_df["Country"] != "xx"]
fixed_df = fixed_df[~fixed_df["Country"].str.contains("\*").astype(bool)]
country_vc = fixed_df["Country"].value_counts()
fixed_df = fixed_df[fixed_df["Country"].isin(country_vc[country_vc == country_vc.max()].index)]

print(fixed_df.shape)
fixed_df.head()

(936, 50)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
nonnan_cols = {
    year: set(fixed_df[fixed_df.year == year].dropna(axis=1).columns)
    for year in fixed_df.year.unique()
}
set.intersection(*nonnan_cols.values())

{'Country', 'year'}

In [9]:
print(
    "\n\n".join([
        "Non-nan columns in {0}: {1}".format(year, ", ".join(['"{0}"'.format(col) for col in cols]))
        for year, cols in nonnan_cols.items()
    ])
)

Non-nan columns in 2015: "Health (Life Expectancy)", "Region", "Freedom", "Happiness Rank", "Happiness Score", "Standard Error", "Dystopia Residual", "Family", "Generosity", "Economy (GDP per Capita)", "year", "Country", "Trust (Government Corruption)"

Non-nan columns in 2016: "Health (Life Expectancy)", "Region", "Upper Confidence Interval", "Freedom", "Happiness Rank", "Happiness Score", "Dystopia Residual", "Family", "Lower Confidence Interval", "Generosity", "Economy (GDP per Capita)", "year", "Country", "Trust (Government Corruption)"

Non-nan columns in 2017: "Dystopia.Residual", "Freedom", "Economy..GDP.per.Capita.", "Happiness.Rank", "Health..Life.Expectancy.", "Trust..Government.Corruption.", "Whisker.high", "Family", "Whisker.low", "Happiness.Score", "Generosity", "year", "Country"

Non-nan columns in 2018: "Healthy life expectancy", "Freedom to make life choices", "Social support", "Generosity", "GDP per capita", "Score", "year", "Country", "Overall rank"

Non-nan columns in 2019: "Healthy life expectancy", "Freedom to make life choices", "Perceptions of corruption", "Social support", "Generosity", "GDP per capita", "Score", "year", "Country", "Overall rank"

Non-nan columns in 2020: "Regional indicator", "Dystopia + residual", "Explained by: Perceptions of corruption", "Healthy life expectancy", "Freedom to make life choices", "Standard error of ladder score", "Explained by: Healthy life expectancy", "Ladder score", "Generosity", "Explained by: Log GDP per capita", "Perceptions of corruption", "year", "Country", "Ladder score in Dystopia", "Explained by: Generosity", "Social support", "lowerwhisker", "upperwhisker", "Explained by: Freedom to make life choices", "Logged GDP per capita", "Explained by: Social support"

Non-nan columns in 2021: "Regional indicator", "Dystopia + residual", "Explained by: Perceptions of corruption", "Healthy life expectancy", "Freedom to make life choices", "Standard error of ladder score", "Explained by: Healthy life expectancy", "Ladder score", "Generosity", "Explained by: Log GDP per capita", "Perceptions of corruption", "year", "Country", "Ladder score in Dystopia", "Explained by: Generosity", "Social support", "lowerwhisker", "upperwhisker", "Explained by: Freedom to make life choices", "Logged GDP per capita", "Explained by: Social support"

Non-nan columns in 2022: "Whisker-high", "Dystopia (1.83) + residual", "Whisker-low", "Explained by: Healthy life expectancy", "Explained by: Generosity", "Explained by: Freedom to make life choices", "Explained by: Perceptions of corruption", "Explained by: Social support", "RANK", "Happiness score", "year", "Country", "Explained by: GDP per capita"

In [10]:
fixed_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 936 entries, 0 to 1229
Data columns (total 50 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     936 non-null    object
 1   Region                                      234 non-null    object
 2   Happiness Rank                              234 non-null    float64
 3   Happiness Score                             234 non-null    float64
 4   Standard Error                              117 non-null    float64
 5   Economy (GDP per Capita)                    234 non-null    float64
 6   Family                                      351 non-null    float64
 7   Health (Life Expectancy)                    234 non-null    float64
 8   Freedom                                     351 non-null    float64
 9   Trust (Government Corruption)               234 non-null    float64
 10  Generosity                                  819 non-null    float64
 11  Dystopia Residual                           234 non-null    float64
 12  year                                        936 non-null    int64
 13  Lower Confidence Interval                   117 non-null    float64
 14  Upper Confidence Interval                   117 non-null    float64
 15  Happiness.Rank                              117 non-null    float64
 16  Happiness.Score                             117 non-null    float64
 17  Whisker.high                                117 non-null    float64
 18  Whisker.low                                 117 non-null    float64
 19  Economy..GDP.per.Capita.                    117 non-null    float64
 20  Health..Life.Expectancy.                    117 non-null    float64
 21  Trust..Government.Corruption.               117 non-null    float64
 22  Dystopia.Residual                           117 non-null    float64
 23  Overall rank                                234 non-null    float64
 24  Score                                       234 non-null    float64
 25  GDP per capita                              234 non-null    float64
 26  Social support                              468 non-null    float64
 27  Healthy life expectancy                     468 non-null    float64
 28  Freedom to make life choices                468 non-null    float64
 29  Perceptions of corruption                   467 non-null    float64
 30  Regional indicator                          234 non-null    object
 31  Ladder score                                234 non-null    float64
 32  Standard error of ladder score              234 non-null    float64
 33  upperwhisker                                234 non-null    float64
 34  lowerwhisker                                234 non-null    float64
 35  Logged GDP per capita                       234 non-null    float64
 36  Ladder score in Dystopia                    234 non-null    float64
 37  Explained by: Log GDP per capita            234 non-null    float64
 38  Explained by: Social support                351 non-null    object
 39  Explained by: Healthy life expectancy       351 non-null    object
 40  Explained by: Freedom to make life choices  351 non-null    object
 41  Explained by: Generosity                    351 non-null    object
 42  Explained by: Perceptions of corruption     351 non-null    object
 43  Dystopia + residual                         234 non-null    float64
 44  RANK                                        117 non-null    float64
 45  Happiness score                             117 non-null    object
 46  Whisker-high                                117 non-null    object
 47  Whisker-low                                 117 non-null    object
 48  Dystopia (1.83) + residual                  117 non-null    object
 49  Explained by: GDP per capita                117 non-null    object
dtypes: float64(36), int64(1), object(13)
memory usage: 325.4+ KB

In [11]:
#https://www.kaggle.com/code/htester/exploratory-data-analysis
#https://www.kaggle.com/code/marcellakomunita/k-means-clustering

In [12]:
# Copy the raw data
df = fixed_df.copy()
# Fix country column name
df.rename(columns={"Country": "country"}, inplace=True)
# Region column
df["region"] = df["country"].replace(df[["country", "Region"]].set_index("country").dropna().to_dict()["Region"])
# Happiness score column
df["happiness_score"] = df["Happiness Score"].fillna(df["Happiness.Score"])\
                                             .fillna(df["Score"])\
                                             .fillna(df["Ladder score"])\
                                             .fillna(df["Happiness score"])\
                                             .astype(str).str.replace(",", ".").astype(float)
# Happiness rank column
df.sort_values(by=["year", "happiness_score"], ascending=[True, False], inplace=True)
df["happiness_rank"] = df.groupby("year").cumcount() + 1
# Drop extra columns
df = df[["year", "country", "region", "happiness_rank", "happiness_score"]]
# Sort values
df = df.sort_values(by=["year", "happiness_rank"]).reset_index(drop=True)
# Print the result
print(df.shape)
df.head()

(936, 5)

   year      country          region  happiness_rank  happiness_score
0  2015  Switzerland  Western Europe               1            7.587
1  2015      Iceland  Western Europe               2            7.561
2  2015      Denmark  Western Europe               3            7.527
3  2015       Norway  Western Europe               4            7.522
4  2015       Canada   North America               5            7.427

In [13]:
! pip install --upgrade pip
! pip install lets_plot -U

Collecting pip
  Using cached pip-23.0.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-23.0.1

ERROR: Could not find a version that satisfies the requirement lets_plot (from versions: none)
ERROR: No matching distribution found for lets_plot

In [43]:
import numpy as np
import pandas as pd

from lets_plot import *
from lets_plot.mapping import *
from lets_plot.geo_data import *
from lets_plot.bistro import *
LetsPlot.setup_html()

ModuleNotFoundError: No module named 'lets_plot'

In [46]:
def bunch2(p1, p2, width=400, height=400):
    bunch = GGBunch()
    bunch.add_plot(p1, 0, 0, width, height)
    bunch.add_plot(p2, width, 0, width, height)
    return bunch.show()

In [45]:
def map_plot(data, year):
    local_df = data[data.year == year]
    countries = geocode_countries(data.country.unique()).inc_res().get_boundaries()
    return ggplot() + \
        geom_livemap(zoom=1) + \
        geom_map(aes(fill="happiness_score"), data=local_df, map=countries, map_join="country", \
                 size=0, alpha=.5, tooltips=layer_tooltips().title("@country")\
                                                            .line("happiness_score|^fill")) + \
        scale_fill_gradient(name="happiness score", low=HS_LOW, high=HS_HIGH, \
                            limits=[data.happiness_score.min(), data.happiness_score.max()]) + \
        ggtitle("Happiness score for each country in {0}".format(year)) + \
        theme(legend_position='bottom')

width, height = 400, 400
bunch = GGBunch()
bunch.add_plot(map_plot(df, YEARS_RANGE[0]), 0, 0, width, height)
bunch.add_plot(map_plot(df, YEARS_RANGE[1]), width, 0, width, height)
bunch.show()

NameError: name 'GGBunch' is not defined